import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Este archivo corre en Node.js — sin APIs de browser ni JSX.

/**
 * Sidebar autogenerada desde la estructura de carpetas de `docs/`.
 * El orden lo dan los prefijos numéricos de carpetas/archivos y los
 * `_category_.json`. Ver https://docusaurus.io/docs/sidebar.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
